on: push
name: Publicar eslint-config para npm

jobs:
    publish:
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Publish
        runs-on: ubuntu-latest

        steps:
            - name: Copiando projeto
              uses: actions/checkout@v3

            - name: Configurando Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
                  always-auth: true
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Instalando dependências
              run: npm install

            - name: Publicando para o NPM
              run: npm publish --access public
