on:
  push:
    branches:
      - main # Publicar apenas quando houver push na branch 'main'

name: Publicar ssp-nest-cli para NPM

jobs:
  publish:
    if: ${{ github.ref == 'refs_heads_main' }}
    name: Publicar Pacote NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          always-auth: true
          cache: "npm"

      - name: Instalar Dependências (npm ci)
        run: npm ci

      - name: Compilar Código TypeScript
        run: npm run build # Este comando compila src/ para dist/ e o 'postbuild' copia collection.json

      # - name: Executar Testes # <--- ADIÇÃO: RODAR TESTES ANTES DE PUBLICAR
      #   run: npm test # Garante que os testes passem antes da publicação

      - name: Publicar para o NPM
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
